# Brewfile — generated by `brew bundle dump --describe` style notes
# Comments and blank lines must be dropped on parse and must NOT appear
# on Write.

# section: taps
tap "homebrew/cask"
tap "homebrew/cask-fonts", "https://github.com/Homebrew/homebrew-cask-fonts.git"

# section: formulae
brew "git"
brew "ripgrep"
brew "vim", args: ["with-python3"]

# section: casks
cask "firefox"
cask "iterm2"

# section: mac app store
mas "Xcode", id: 497799835
